nsamples: 3001
sampling_rate: 100
labeler: gaussian    # gaussian | triangle | box
sigma: 10            # Half-width of labeler
add_fake_events: 200   # Copying events increase training data set (in percent)
# phases: PS
datasets:
    - insheim: /scratch/gpi/seis/jheuel/ai_datasets/insheim
batch_size: 256
epochs: 20
learning_rate:
    decay: True
    initial_lr: 0.1
    step_size: 10
    gamma: 0.1
preload_model: stead  # diting, ethz, geofon, instance, iquique, lendb, neic, obs, original, scedc, stead
nworkers: 6
patience: 50        # early stopping
model_name: test_floodrisk.pth
# Parameters for test
win_len_factor: 10
true_pick_prob: 0.5
arrival_residual: 10  # in samples